### ISSUE TITLE
Serve routes button JS

### ISSUE THREAD

**Issue by RachBLondon** [nikhilaravi/learn-node#13]
Thanks for this tutorial its been super helpful. But I wanted to ask one question, in the server routes section I can see you have created an XMLhttp request at attached to a button, where would you put this javascript, would it be in a front end js file? and then do I link using the normal script tag at the bottom of the index.html page?

Thanks

https://github.com/nikhilaravi/learn-node#server-routes

**Comment by msmichellegar** [comment]
@RachBLondon Yep, that would be in a frontend JS file. Exactly as you described. You just need to hook it up to the button :)

**Comment by RachBLondon** [comment]
Thanks
