### ISSUE TITLE
Button ? Server routes

### ISSUE THREAD

**Issue by tormod17** [nikhilaravi/learn-node#9]
I'm just trying to go through this guide to get a better understanding and it's way clearer the second time -- phew!! just wanted to know what button are you referring to in the 'Server routes' section is this just a hypothetical button that you may have in your HTML that when click  would send the request?

**Comment by nikhilaravi** [comment]
Hi Tormod, sorry for the late reply! yes I was just referring to a hypothetical button. I'm updating the readme today so hopefully it will be clearer!
